services:
  collector:
    # TODO convert to ADOT
    image: otel/opentelemetry-collector
    expose:
      - 4317 # otlp grpc
      - 4318 # otlp http
    ports:
      - "127.0.0.1:4317:4317" # otlp grpc
      - "127.0.0.1:4318:4318" # otlp http
    volumes:
      - ./otel-config.yml:/etc/otel-config.yaml
    command: "--config=/etc/otel-config.yaml"
    depends_on:
      - jaeger

  jaeger:
    image: jaegertracing/all-in-one:1.57
    # Enable OTLP export of traces from OTel Collector to Jaeger
    environment:
      COLLECTOR_OTLP_ENABLED: true
    # Expose Jaeger's OTLP ports so the OTel Collector can write to Jaeger
    expose:
      - 4317 # otlp grpc
      - 4318 # otlp http
      - 14269 # jaeger collector, admin port
      - 5778 # serves sampling strategies
    ports:
      - "127.0.0.1:16686:16686" # jaeger ui

volumes:
    pg_data:
